export const actions = {
  SET_IS_LOADING: "SET_IS_LOADING",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_FILTERED_PRODUCTS: "SET_FILTERED_PRODUCTS",
  SET_PRICE_RANGE: "SET_PRICE_RANGE",
  SET_SORT_BY: "SET_SORT_BY",
  SET_PROCESS_CATEGORY_FILTER: "SET_PROCESS_FILTER",
  SET_VARIETY_FILTER: "SET_VARIETY_FILTER",
  SET_COUNTRY_FILTER: "SET_COUNTRY_FILTER",
  RESET: "RESET"
};
