# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    - run: |
          if [ -e server/package-lock.json ]; then
          cd server
          npm install
          elif [ -e server/package-lock.json ]; then
          cd server
          npm ci
          else
          cd server
          npm i
          fi
    - run: |
          cd server
          npm run build --if-present
          npm run build
    
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    - run: |
          if [ -e client/package-lock.json ]; then
          cd client
          npm install
          elif [ -e client/package-lock.json ]; then
          cd client
          npm ci
          else
          cd client
          npm i
          fi
    - run: |
          cd client
          npm run build --if-present
          npm run build
