name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        env:
          CI: false
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd server
          sudo npm ci
          cd ../client
          sudo npm ci
          sudo npm run build
